CREATE TABLE [dbo].[ApiPreference] (	
    [ApiPreferenceID]						INTEGER IDENTITY(1,1)	NOT NULL,
    [ApiPreferenceObject_id]				NVARCHAR(40)			NOT NULL,
    [AdminApiKeyAppFlag]					BIT 					NULL,
    [LeaderBoardAnonymousFlag]				BIT 					NULL,
	[LeaderBoardRankFlag]					BIT 					NULL,
	[LeaderBoardAvatarFlag]					BIT 					NULL,
	[LeaderBoardNameFlag]					BIT 					NULL,
	[LeaderBoardSecurityMaturityFlag]		BIT 					NULL,
	[LeaderBoardPointsFlag]					BIT 					NULL,
	[LeaderBoardAccuracyFlag]				BIT 					NULL,
	[LeaderBoardTimeSpentFlag]				BIT 					NULL,
	[LeaderBoardJoinDateFlag]				BIT 					NULL,
	[LeaderBoardConfidenceLevelFlag]		BIT 					NULL,
	[LeaderBoardDeltaFlag]					BIT 					NULL,
	[IntegrationGoogleDocsFlag]				BIT 					NULL,
	[IntegrationInterComAppFlag]			BIT 					NULL,
	[IntegrationUserSnapAppFlag]			BIT 					NULL,
	[PrivacyUserCommunicationsFlag]			BIT 					NULL,
	[PrivacySocialFlag]						BIT 					NULL,
	[PrivacyPublicProfileFlag]				BIT 					NULL,
	[DigestCompanyAdminWeeklyFlag]			BIT 					NULL,
	[DigestCompanyAdminMonthlyFlag]			BIT 					NULL,
	[DigestCompanyAdminQuarterlyFlag]		BIT 					NULL,
	[DigestTeamManagerWeeklyFlag]			BIT 					NULL,
	[DigestTeamManagerMonthlyFlag]			BIT 					NULL,
	[DigestTeamManagerQuarterlyFlag]		BIT 					NULL,
	[CommunicationsFromEmail]				NVARCHAR(100)			NULL,
	[CommunicationsFromName]				NVARCHAR(100)			NULL,
	[CommunicationsRegistrationEmailFlag]	BIT 					NULL,
	[LabAvailbilityFlag]					BIT 					NULL,
	[SenseiCompanyAdminDefaultRulesFlag]	BIT 					NULL,
	[SenseiFeedbackFlag]					BIT 					NULL,
	[SenseiDataCollectionFlag]				BIT 					NULL,
	[SenseiRulesetURLFlag]					BIT 					NULL,
	[StatisticsSecurityMaturityFlag]		BIT 					NULL,
	[CreatedDate]							DATETIME2				NOT NULL, -- from properties of _id
	[LastModifiedUTCDate]					DATETIME2				NOT NULL,
    
	CONSTRAINT PK_ApiPreference PRIMARY KEY CLUSTERED ([ApiPreferenceID])

);
