CREATE TABLE [dbo].[stgCourses]
(
	[stgCoursesID]		BIGINT IDENTITY (1,1)	NOT NULL,
	[ChangeStreamDetails]	NVARCHAR(MAX)	NOT NULL,
	[InsertedUTCDate]		DATETIMEOFFSET	NOT NULL	CONSTRAINT DF_stgCourses_InsertedUTCDate DEFAULT GETUTCDATE() ,

	CONSTRAINT PK_stgCourses PRIMARY KEY CLUSTERED ([stgCoursesID])
)
