
CREATE TABLE [dbo].[stgQuests]
(
	[stgQuestsID]		BIGINT IDENTITY(1,1)	NOT NULL,
    [ChangeStreamDetails]	NVARCHAR(MAX)	NOT NULL,
	[InsertedUTCDate]		DATETIMEOFFSET	NOT NULL	CONSTRAINT DF_stgQuests_InsertedUTCDate DEFAULT GETUTCDATE() ,

	CONSTRAINT PK_stgQuests PRIMARY KEY CLUSTERED ([stgQuestsID])
)
