CREATE TABLE [dbo].[stgRealms]
(
	[stgRealmsID]		BIGINT IDENTITY (1,1)	NOT NULL,
	[ChangeStreamDetails]	NVARCHAR(MAX)	NOT NULL,
	[InsertedUTCDate]		DATETIMEOFFSET	NOT NULL	CONSTRAINT DF_stgRealms_InsertedUTCDate DEFAULT GETUTCDATE() ,

	CONSTRAINT PK_stgRealms PRIMARY KEY CLUSTERED ([stgRealmsID])
)
