CREATE TABLE [dbo].[stgState]
(
	[stgStateID]		BIGINT IDENTITY (1,1)	NOT NULL,
	[ChangeStreamDetails]	NVARCHAR(MAX)	NOT NULL,
	[InsertedUTCDate]		DATETIMEOFFSET	NOT NULL	CONSTRAINT DF_stgState_InsertedUTCDate DEFAULT GETUTCDATE() ,

	CONSTRAINT PK_stgState PRIMARY KEY CLUSTERED ([stgStateID])
)
